<?php


use \Drupal\dr8booking\Functions\fun;

/**
 * Implements hook_theme().
 */
function dr8booking_theme($existing, $type, $theme, $path) {
  return [
    'booked_users' => [
      'variables' => [
        'content' => 'from hook module',
      ],
    ],
  ];
}

function dr8booking_page_attachments_alter(array &$page) {
  $page['#attached']['library'][] = 'dr8booking/dr8booking_lib';
  $nid = NULL;
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->getType() == 'booking_item') {
    $nid = $node->id();
    $node = fun::getNode($nid);
    $page['#attached']['drupalSettings']['dr8booking']['node'] = [
      'id' => $node['id'],
      'status' => $node['status'],
    ];
  }
  else{
    $page['#attached']['drupalSettings']['dr8booking']['node'] = NULL;
  }
}

